Authentication
NeskladAnya/test-guru pull request #11
Opened 2021-12-03 18:11 UTC by NeskladAnya

2021-12-04 14:00 UTC, VidgarVii requested changes

2021-12-04 14:00 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +      cookies[:intended_url] = request.url
:+1:

2021-12-04 14:00 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +    cookies[:email] = current_user&.email
1 задача метода не пускать в систему не залогиненного юзера. Запись cookies[:email] не входит в задачи метода. Тем более эта операция будет совершать КАЖДЫЙ раз для аутентифицированного юзера.
2 данная операция безполезная. Так как всё-ровно не используется

2021-12-04 14:00 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +      redirect_to(cookies[:intended_url] || tests_path)
Вот здесь можно сразу удалить данные из кук. delete возвращает значение, которое удалил

```ruby
redirect_to destination_path
...
private
def destination_path
  cookies.delete(:intended_url) || tests_path
end
```

2021-12-04 14:00 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +      cookies[:intended_url] = nil
лучше полностью удаляй запись. Ключи со значением nil плохая практика.

2021-12-04 14:00 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +    session[:user_id] = nil
тоже самое про нил

2021-12-04 14:00 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @user = User.find(session[:user_id])
[тут](https://github.com/NeskladAnya/test-guru/pull/11/files#diff-766c34fd6533171eaf54300c153f89d6002c35c02cfc9c5b219251f85180ad07R18) тут уже создала волшебный хелпер метод, который можно использовать везде где нужен текущий юзер

Его так же хорошо использовать в экшене create
А вот author_id из test_params и формы лучше убрать. Это может с играть плохую шутку. Как правило юзеры регистрируются быстро. И загрузка всей таблицы юзеров приведёт к тому, что страница просто не загрузится

2021-12-07 07:08 UTC, VidgarVii requested changes

2021-12-07 07:08 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +      destination_path
что делаем метод destination_path? возвращает путь куда надо отправить юзера. А смысл вызывать этот метод если он не используется и не передаётся в redirect_to?

2021-12-07 07:08 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @user = current_user
Давай еще раз.
Надо использовать метод current_user. Ведь этот метод вернёт текущего юзера. Нет смысла писать в переменную @user значение current_user

2021-12-07 07:08 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @test.author_id = current_user.id
тут сразу 2 момента
1 Используй методы ассоциации. Так будет сразу понятно для кого и что создаём `current_user.created_tests.build(test_params)`
2 При объявлении связи нет смысла обращаться по ид. Используют объекты. Посмотри как в сидах у тебя указан автор

2021-12-07 14:18 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +      cookies.delete(:intended_url) || tests_path
приму на счёт, что просто день тяжёлый
тут просто надо сделать так
```ruby
  redirect_to(destination_path)
else
...

private

def destination_path
  cookies.delete(:intended_url) || tests_path
end
```

2021-12-07 18:28 UTC, NeskladAnya commented on app/controllers/sessions_controller.rb
> +      cookies.delete(:intended_url) || tests_path
Да, что-то пошло не так :)

2021-12-07 18:28 UTC, merged