Javascript
NeskladAnya/test-guru pull request #16
Opened 2022-05-06 18:45 UTC by NeskladAnya

2022-05-07 15:16 UTC, VidgarVii requested changes

2022-05-07 15:16 UTC, VidgarVii commented on app/javascript/utilities/password_match.js
> +}
No new lina at end of file
таких вещей категорически не должно быть в коде

2022-05-07 15:16 UTC, VidgarVii commented on app/javascript/utilities/password_match.js
> +
следи за чистотой в коде. Куда нам такие отступы?

2022-05-07 15:16 UTC, VidgarVii commented on app/javascript/utilities/password_match.js
> +  var password_confirmation = document.getElementById('user_password_confirmation').value
Время глобальных var-ов прошло. при объявлении переменных используй let/const. Так безопасней и код становиться понятней. Обязательно по гугли отличие!

2022-05-07 15:16 UTC, VidgarVii commented on app/javascript/utilities/password_match.js
> +  var password_confirmation = document.getElementById('user_password_confirmation').value
при каждом изменении поля происходит поиск элементов. Эта операция очень дорогая и долгая. Выноси поиск элементов за пределы события

2022-05-07 15:16 UTC, VidgarVii commented on app/javascript/utilities/password_match.js
> +  this.addEventListener('click', checkPasswordFields)
1 addEventListener считается очень затратной операций и не стоит её вешать на целое окно. Лучше ориентироваться на конкретный ДОМ элемент
2 получается функция checkPasswordFields будет запускаться на всех страницах и в консоль будет ссыпаться куча ошибок

2022-05-07 15:16 UTC, VidgarVii commented on app/javascript/utilities/password_match.js
> +  }
ооооочень медленный скрипт получился и подвержен багам.
Каждый раз ориентироваться на объект window очень сомнительное решение. Работают обычно с ДОМ элементами внутри документа, а не с окном.
И про постоянный поиск элементов уже отписал. Зачем каждый раз искть один и тот же элемент? Еще учитывая что обращение идёт чере this то на левой странице сайта действительно может быть элемент с классом .octicon-alert (очень слабое название для поиска НУЖНОГО элемента), то мы может просто сломать вверстку на странице

2022-05-08 16:42 UTC, NeskladAnya commented
Add JavaScript functionality

2022-05-08 16:42 UTC, merged