Rails controller
NeskladAnya/test-guru pull request #7
Opened 2021-11-10 15:28 UTC by NeskladAnya

1. Created tests and questions resources.
2. Generated questions_controller.
3. Created the HTML form to add a new question.

2021-11-10 16:43 UTC, VidgarVii requested changes

2021-11-10 16:43 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  before_action :find_test
нам не всегда нужен тест. Например для show достаточно знать ИД ресурса

посмотри командой rails routes какие пути у тебя сейчас сформированы. А потом добавь опцию shallow true в роутах
```
resources :questions, shallow: true
```
и сравни
Пути станут короче. И меньше придется делать запросов в БД. Всегда используют этот shallow

2021-11-10 16:43 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  end
При создании и обновлении ресурса нужно проверять валидацию, которая была прописана в модели. И если валидация не прошла, то рендерят форму и выводит ошибки(ошибки будем показывать далее по уроку)
По этому тут надо условие записался ли объект в базу?
стандартный подход экшена create такой
```
@question = @test.questions.build(question_params)
if @question.save
  redirect_to @question
else
  render :new
end
```

2021-11-10 16:43 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  before_action :find_test_questions
и соответственно нам не всегда нужно знать список всех вопросов. Эта не нужная операция сильно замедлит работу других экшенов

2021-11-10 16:43 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    params.require[:questions].permit(:body)
require(:questions)

2021-11-10 16:43 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +<form action="/tests/7/questions" method="post">
ид теста надо передавать параметром запроса.

2021-11-11 09:02 UTC, NeskladAnya commented on app/views/questions/new.html.erb
> +<form action="/tests/7/questions" method="post">
Честно говоря, пока что не разобралась, как передавать. В задании указано: "Идентификатор теста к которому принадлежит вопрос можно указать явно в составе URL значения атрибута action в тэге form". И в теории про это тоже пока что ничего не упоминалось.

2021-11-11 10:00 UTC, VidgarVii requested changes

2021-11-11 10:00 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +<form action="/tests/7/questions" method="post">
точно так же как полуаем параметры запроса в контроллере
/tests/#{params[:test_id]}/questions

2021-11-11 10:02 UTC, VidgarVii requested changes

2021-11-11 10:02 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      render inline: '<%= @question.inspect %>'
лучше сразу отправлять юзера на страницу вопроса. 
redirect_to @question

2021-11-11 10:02 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  end
после удаление юзера хорошо бы куда-то отправить. На страницу всех вопросов теста например

2021-11-12 11:49 UTC, merged